export const logos = [
  {
    type: "frontend",
    name: "JavaScript",
    colour: "F7DF1E",
    logo: "javascript",
  },
  {
    type: "frontend",
    name: "TypeScript",
    colour: "007ACC",
    logo: "typescript",
  },
  {
    type: "frontend",
    name: "HTML5",
    colour: "E34F26",
    logo: "html5",
  },
  {
    type: "frontend",
    name: "CSS",
    colour: "239120",
    logo: "css3",
  },
  {
    type: "backend",
    name: "Java",
    colour: "ED8B00",
    logo: "openjdk",
  },
  {
    type: "backend",
    name: "Python",
    colour: "3776AB",
    logo: "python",
  },
  {
    type: "backend",
    name: "Ruby",
    colour: "CC342D",
    logo: "ruby",
  },
  {
    type: "backend",
    name: "C%2B%2B",
    colour: "00599C",
    logo: "c%2B%2B",
  },
  {
    type: "backend",
    name: "C",
    colour: "00599C",
    logo: "c",
  },
  {
    type: "backend",
    name: "C%23",
    colour: "239120",
    logo: "c-sharp",
  },
  {
    type: "libraries",
    name: "ROS",
    colour: "22314E",
    logo: "ros",
  },
  {
    type: "libraries",
    name: "Material--UI",
    colour: "007FFF",
    logo: "mui",
  },
  {
    type: "cloud",
    name: "Amazon_AWS",
    colour: "232F3E",
    logo: "amazon-aws",
  },
  {
    type: "cloud",
    name: "Docker",
    colour: "2496ED",
    logo: "docker",
  },
  {
    type: "cloud",
    name: "GitHub_Actions",
    colour: "2088FF",
    logo: "github-actions",
  },
  {
    type: "environments",
    name: "Windows",
    colour: "0078D6",
    logo: "windows",
  },
  {
    type: "environments",
    name: "Ubuntu",
    colour: "E95420",
    logo: "ubuntu",
  },
  {
    type: "environments",
    name: "VS_Code",
    colour: "0078D4",
    logo: "visual%20studio%20code",
  },
  {
    type: "environments",
    name: "Eclipse",
    colour: "2C2255",
    logo: "eclipse",
  },
  {
    type: "other",
    name: "Unity",
    colour: "100000",
    logo: "unity",
  },
];
